# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import quadratic_pb2 as quadratic__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in quadratic_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class QuadraticSolverStub(object):
    """The quadratic solver service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SolveQuadratic = channel.unary_unary(
                '/quadratic.QuadraticSolver/SolveQuadratic',
                request_serializer=quadratic__pb2.QuadraticRequest.SerializeToString,
                response_deserializer=quadratic__pb2.QuadraticReply.FromString,
                _registered_method=True)


class QuadraticSolverServicer(object):
    """The quadratic solver service definition.
    """

    def SolveQuadratic(self, request, context):
        """Solves a quadratic equation 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuadraticSolverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SolveQuadratic': grpc.unary_unary_rpc_method_handler(
                    servicer.SolveQuadratic,
                    request_deserializer=quadratic__pb2.QuadraticRequest.FromString,
                    response_serializer=quadratic__pb2.QuadraticReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quadratic.QuadraticSolver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quadratic.QuadraticSolver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuadraticSolver(object):
    """The quadratic solver service definition.
    """

    @staticmethod
    def SolveQuadratic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quadratic.QuadraticSolver/SolveQuadratic',
            quadratic__pb2.QuadraticRequest.SerializeToString,
            quadratic__pb2.QuadraticReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
