# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quadratic.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fquadratic.proto\x12\tquadratic\"B\n\x10QuadraticRequest\x12\x0e\n\x06\x63oeffa\x18\x01 \x01(\x02\x12\x0e\n\x06\x63oeffb\x18\x02 \x01(\x02\x12\x0e\n\x06\x63oeffc\x18\x03 \x01(\x02\"\"\n\x0eQuadraticReply\x12\x10\n\x08solution\x18\x04 \x01(\t2]\n\x0fQuadraticSolver\x12J\n\x0eSolveQuadratic\x12\x1b.quadratic.QuadraticRequest\x1a\x19.quadratic.QuadraticReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quadratic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUADRATICREQUEST']._serialized_start=30
  _globals['_QUADRATICREQUEST']._serialized_end=96
  _globals['_QUADRATICREPLY']._serialized_start=98
  _globals['_QUADRATICREPLY']._serialized_end=132
  _globals['_QUADRATICSOLVER']._serialized_start=134
  _globals['_QUADRATICSOLVER']._serialized_end=227
# @@protoc_insertion_point(module_scope)
